name: "Build package and demo site, deploy to GH Pages"

on:
  pull_request:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.10.0

      - name: Run arbitrary commands
        run: devbox run build
