name: "Deploy demo site"

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - uses: cachix/cachix-action@v12
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install tarball+https://install.devenv.sh/latest
        shell: sh
      - run: nix develop --impure -c pnpm install
      - run: nix develop --impure -c build-package
      - run: nix develop --impure -c build-demo
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload built demo.
          path: "./demo/dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
