name: "Deploy demo site"

on:
  pull_request:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  nix-install-and-build:
    if: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v20

      - uses: cachix/cachix-action@v12
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile install github:cachix/devenv/latest
        shell: sh

      - name: Install dependencies
        run: nix develop --impure -c pnpm install -r --shamefully-hoist

      - name: Build package
        run: nix develop --impure -c build-package

      - name: Build demo site
        run: nix develop --impure -c build-demo

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload built demo.
          path: "./demo/dist"
