name: "Build pacakge and demo site (Nix)"

on:
  pull_request:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  nix-install-and-build:
    if: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Install dependencies
        run: nix develop --impure -c pnpm install -r --shamefully-hoist

      - name: Build package
        run: nix develop --impure -c build-package

      - name: Build demo site
        run: nix develop --impure -c build-demo

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload built demo.
          path: "./demo/dist"
