name: "Publish package to NPM"

on:
  push:
  release:
    types: [published]

jobs:
  build:
    steps:
      - uses: ./.github/workflows/basic.yml
      - run: pnpm publish --dry-run -w ./packages/cooklang
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
