name: "Publish package to NPM"

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build output
        uses: ./.github/workflows/basic.yml
      - run: pnpm publish --dry-run -w ./packages/cooklang
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
